language: python
matrix:
  include:
  - python: 3.4
    env:
    - TOXENV=py34
  - python: 3.5
    env:
    - TOXENV=py35
  - python: 3.6
    env:
    - TOXENV=py36
  - python: 3.7
    env:
    - TOXENV=py37
  - python: pypy3
    env:
    - TOXENV=pypy3
install:
- pip install tox coveralls
script:
- tox
after_success:
- coveralls
deploy:
  provider: pypi
  user: mattdavis90
  distributions: sdist bdist_wheel
  on:
    condition: "$TOXENV == py37"
    tags: true
    all_branches: true
    repo: mattdavis90/promptr
  password:
    secure: D2DMoDJU6g+e0wy25aC62tvtLvRq34z1eqWePWl/2WduaV22WJTSo5QIH/WGXAcLyHsuXjQ/M9An4MxeOa0cxU4+S7otuP8VKZKW6YH/CUUhI1kmTiGl6nA279i60iUAbzZ8mSwhkQKLiiN5/+TdoY+9XiRmlOG04c7uHsp4zfNZV1s0MmRovN0N4fxuL9Xl69KLGb3UY2a3At2N2XVrofezufxaNrGAvPAivZC31cM86qL8vpqeir0Zq5+UlzVHntNm2sOlU1aoErNzKt8sybgbivOHpEb+RBbdLu/WtMPUXq9SjOh6d4O0zQPxkkNnSQ5vTr6RV2VNHJdmTTyyb1XtyAeQir6ft2PUw2cmiZDSf2zSyL1nu2UVpAObSiKnCHohbMeWwGt/5s+ZYg1lY72DDMflU4gb2zrhjiPIhgtv6+v5JwK1y06UFGQ5c4kozfGGsRXPCDVt75lOPJDkd0gRYkLNYXUw5xiwG9Q+gkmISy3YUk0HaYj8uG6eYrAapuam6z5HpCPCAy6BF3gibsWj+LeagXXZPhukiMKpWXDhsTYiuGbrCIgl98uTu8SPNJ/EauOjRSL6O+2QAuibyFkaRZcXz3Q7i3r55UyslPGKF5e/gU0JMUHL1Ejb6Hsbb5lKDqVKO4Tdp1AsKVmAaDBJ+0pFg/XCpoZ0J0uNbm8=
